name: Bug Report
description: File a bug report
title: "M00-LAB00: QUICK_DESCRIPTION"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this bug report!

        **Replace issue name "M00-LAB00: QUICK_DESCRIPTION" with the correct lab and short description**  
        Example: **M03-LAB13: Conditional Access policy cannot be created**

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info 😉?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue and how to reproduce it
      placeholder: Tell us what you see!
      value: |
        Exercise: 00
        Task: 00
        Step: 00

        Description of issue:

        Reproduction steps:
        1.
        1.
        1.
    validations:
      required: true

  - type: dropdown
    id: lab
    attributes:
      label: Lab
      description: Select the SC-300 lab
      options:
        - Other
        - Lab 00 SetUpLabResources
        - Lab 01 ManageUserRoles
        - Lab 02 WorkingWithTenantProperties
        - Lab 03 AssignLicensesToUsersByGroupMembershipAAD
        - Lab 04 ConfigureExternalCollaborationSettings
        - Lab 05 AddGuestUsersToTheDirectory
        - Lab 06 AddFederatedIdentityProvider
        - Lab 07 AddHybridIdentityWithAzureADConnect
        - Lab 08 EnableAzureADMultifactorAuthentication
        - Lab 09 ConfigureAndDeploySelfServicePasswordReset
        - Lab 10 AzureADAuthenticationForWindowsAndLinuxVM
        - Lab 11 AssignAzureResourcesRolesInPrivilegedIdentityManagement
        - Lab 12 ManageAzureADSmartLockoutValues
        - Lab 13 ImplementAndTestAConditionalAccessPolicy
        - Lab 14 EnableSignInRiskPolicy
        - Lab 15 ConfigureAAD_MultiFactorAuthRegPolicy
        - Lab 16 UsingAzureKeyVaultForManagedIdentities
        - Lab 17 DefenderForCloudAppsDiscoveryAndRestrictions
        - Lab 18 DefenderForCloudAppsAccessPolicies
        - Lab 19 RegisterAnApplication
        - Lab 20 ImplementAccessManagementForApps
        - Lab 21 GrantTenantWideAdminConsentToAnApplication
        - Lab 22 CreateAndManageACatalogOfResourcesInAADEntitlementManagement
        - Lab 23 AddTermsOfUseAcceptanceReporting
        - Lab 24 ManageTheLifecycleOfExternalUsersInAADIdentityGovernanceSettings
        - Lab 25 CreatingAccessReviewsForUsers
        - Lab 26 ConfigurePrivilegedIdentityManagementForAADRoles
        - Lab 27 MicrosoftSentinelKustoQueries
        - Lab 28 MonitorIdentitySecureScore
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Relevant screenshots
      description: Please copy and paste any relevant screenshots 📸
      value: paste here 😉

  - type: checkboxes
    id: terms
    attributes:
      label: Do you want to help us? 👏
      description: GitHub uses Pull Requests (PRs) to propose and collaborate on changes. Follow the Contribution Guide in the SC-300 repository.
      options:
        - label: Create a Pull Request following the project's Contribution Guide
          required: false
